---
- name: Testing andrewrothstein.opentelemetry_collector
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'otelcol --version'
      ansible.builtin.command: otelcol --version
      changed_when: false
      register: otelcol_test_output
    - name: Output from 'otelcol --version'
      ansible.builtin.debug:
        msg: '{{ otelcol_test_output.stdout }}'
    - name: Executing 'otelcol-contrib --version'
      ansible.builtin.command: otelcol-contrib --version
      changed_when: false
      register: otelcol_contrib_test_output
    - name: Output from 'otelcol-contrib --version'
      ansible.builtin.debug:
        msg: '{{ otelcol_contrib_test_output.stdout }}'
