---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/otelcol --version
    register: otelcol_test_output
  - name: otelcol --version
    debug:
      msg: '{{ otelcol_test_output.stdout }}'
