---
- name: Resolving vars for {{ otelcol_app }}:{{ otelcol_ver }}
  ansible.builtin.include_vars:
    file: app-install-vars.yml
- name: Looking for install in {{ otelcol_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ otelcol_install_dir }}'
  changed_when: false
  register: otelcol_binary
- name: Downloading and installing otel app
  when: not otelcol_binary.stat.exists
  block:
    - name: Downloading {{ otelcol_url }} to {{ otelcol_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ otelcol_url }}'
        dest: '{{ otelcol_tmp_archive }}'
        mode: '644'
        checksum: '{{ otelcol_checksum }}'
    - name: Mkdir {{ otelcol_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ otelcol_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ otelcol_tmp_archive }} to {{ otelcol_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ otelcol_tmp_archive }}'
        dest: '{{ otelcol_install_dir }}'
        creates: '{{ otelcol_install_exe }}'
  always:
    - name: Rm {{ otelcol_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ otelcol_tmp_archive }}'
        state: absent
- name: Linking {{ otelcol_install_link }} to {{ otelcol_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ otelcol_install_exe }}'
    dest: '{{ otelcol_install_link }}'
    state: link
